### ISSUE TITLE
Class probabilities for snapml.SupportVectorMachin

### ISSUE THREAD

**Issue by saipankaj1212** [IBM/snapml-examples#15]
After fitting the snap ML SVM model, 
decision_function(X, n_jobs=None) 
gives a single confidence score. But I want confidence score for both classes for my both classes of my binary classifier. 
I want output shape as shape as  (n_sample, n_classes)
Suggestions are welcome

**Comment by tdoublep** [comment]
Hi @saipankaj1212. Thank you for opening and issue and asking this question.

SVM's don't naturally produce probability estimates per class. The standard approach for getting class probabilities is to perform an additional _calibration_ step. 

scikit-learn provides a [nice implementation of calibration](https://scikit-learn.org/stable/modules/generated/sklearn.calibration.CalibratedClassifierCV.html) that is compatible with Snap ML's SVM.

Here is an end-to-end example of how to use SVM from snapml with the calibration from scikit-learn:
```python
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from snapml import SupportVectorMachine
from sklearn.calibration import CalibratedClassifierCV

X,y = make_classification(n_samples=10_000, n_features=20, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

clf = CalibratedClassifierCV(
    base_estimator=SupportVectorMachine() 
)

clf.fit(X_train, y_train)

proba = clf.predict_proba(X_test)

print(proba)
``` 
produces:
```bash
$ python test.py 
[[0.16951254 0.83048746]
 [0.06670135 0.93329865]
 [0.00711942 0.99288058]
 ...
 [0.07058149 0.92941851]
 [0.41588043 0.58411957]
 [0.04848692 0.95151308]]
 ```
 
 Hope this helps - let us know if you have any further questions.

**Comment by saipankaj1212** [comment]
Thanks a lot sir...
