### ISSUE TITLE
Windows 11 x64-based processor error ( Microsoft Visual C++ Redistributable for Visual Studio 2019 Installed)

### ISSUE THREAD

**Issue by arthurserres** [IBM/snapml-examples#25]
Hello, after installing via annaconda as explained in the read me, I do not manage to completely run the graph feature preprocessor example. More precisely, in the fourth cell I obtain the error message 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[c:\Users\aserres\snapml-examples\examples\graph_feature_preprocessor\graph_feature_preprocessor.ipynb](file:///C:/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb) Cell 8 line 4
      [1](vscode-notebook-cell:/c%3A/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb#W6sZmlsZQ%3D%3D?line=0) # Create a Graph Feature Preprocessor, set its configuration using the above dictionary and verify it
      [3](vscode-notebook-cell:/c%3A/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb#W6sZmlsZQ%3D%3D?line=2) print("Creating a graph feature preprocessor ")
----> [4](vscode-notebook-cell:/c%3A/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb#W6sZmlsZQ%3D%3D?line=3) gp = GraphFeaturePreprocessor()
      [6](vscode-notebook-cell:/c%3A/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb#W6sZmlsZQ%3D%3D?line=5) print("Setting the parameters of the graph feature preprocessor ")
      [7](vscode-notebook-cell:/c%3A/Users/aserres/snapml-examples/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb#W6sZmlsZQ%3D%3D?line=6) gp.set_params(params)

File [c:\Users\aserres\AppData\Local\anaconda3\envs\snapmlenv\lib\site-packages\snapml\GraphFeaturePreprocessor.py:115](file:///C:/Users/aserres/AppData/Local/anaconda3/envs/snapmlenv/lib/site-packages/snapml/GraphFeaturePreprocessor.py:115), in GraphFeaturePreprocessor.__init__(self)
    114 def __init__(self):
--> 115     self.preproc = libsnapml.gf_allocate()
    117     self.params = {
    118         "num_threads": 12,  # number of software threads to be used
    119         "time_window": -1,
   (...)
    277         "lc-cycle_bins": [2, 3, 4, 5, 6, 7, 8, 9, 10],
    278     }
    279     libsnapml.gf_set_params(self.preproc, self.params)

AttributeError: module 'snapml.libsnapmllocal3_avx2' has no attribute 'gf_allocate'`

Do you have any suggestion to solve this issue ? Thanks by advance.

Best,

Arthur SERRES

**Comment by tdoublep** [comment]
Unfortunately the Graph preprocessor is currently not supported on Windows. We have opened an issue on our side to better document this limitation. Perhaps you could give it a try via WSL or a Linux VM? 

Tagging @jovan-blanusa so he is aware.

**Comment by arthurserres** [comment]
Oh I see thanks a lot for this quick answer ! I spent quite a long time searching but did not find that Graph preprocessor is not supported on windows, is there somwhere we can find thi info ? Also thanks for the suggestion, Linux VM is definitely a good Idea ! I also have a mac M1 but I understood support is only for intel processor right ?

**Comment by tdoublep** [comment]
@arthurserres That's correct, we don't support M1 currently (only Intel x86 on Mac).

**Comment by arthurserres** [comment]
Thanks a lot for the feedback, for now I will use colab for public data and try to go with a Linux VM for sensible ones. PLease let me know if you manage to have windows support :) Otherwise thanks a lot for your work it is super usefull!
