### ISSUE TITLE
GraphFeaturePreprocessor batch size

### ISSUE THREAD

**Issue by arthurserres** [IBM/snapml-examples#26]
Hello, I use the GraphFeaturePreprocessor class and in the example it is mentionned that we can use batch of transaction for computation. I tried to look at the documentation but did not find anything about it. Could you tell me how we can use it in the fit_transform function and what it actually does? Indeed I have a huge dataset but only limited computational power so I assume it can help me :) 

Thanks a lot by advance.

**Comment by andreea-anghel** [comment]
Hi @arthurserres 

The example [here](https://github.com/IBM/snapml-examples/blob/main/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb) shows how to run `fit_transform` with a batch of transactions (`X_train` has 12 transactions). The same for the `transform` function which is also applied to a batch of transactions (`X_test` has 8 transactions). For details, these functions are documented [here](https://snapml.readthedocs.io/en/latest/graph_preprocessor.html). 

For example, if you want to run inference on a large number of transactions, you may want to split the transactions into batches and call `transform` for each batch. If you're interested in generating the initial (in-memory) graph of transactions in steps, you may want to use the `partial_fit` function that updates an existing graph with new transactions. Let us know if you have further questions.

Tagging @jovan-blanusa so he is aware.

**Comment by arthurserres** [comment]
Thanks a lot for the clarification. It makes a lot of sense.

Have a great day and thanks for your work.
