### ISSUE TITLE
Column values mismatch after fit_transform

### ISSUE THREAD

**Issue by fabecode** [IBM/snapml-examples#27]
Hello, 
I tried following the [example GFP tutorial](https://github.com/IBM/snapml-examples/blob/main/examples/graph_feature_preprocessor/graph_feature_preprocessor.ipynb) but using a different dataset input. However, this results in the column values of `EdgeID, SourceAccountId, TargetAccountId and Timestamp` in enriched transactions being different from the original after `fit_transform`. It seems to be reading column-wise but populating row-wise.

Before `fit_transform`:
<img width="224" alt="Screenshot 2024-03-13 123709" src="https://github.com/IBM/snapml-examples/assets/65911192/1ca1b2f4-92b4-48af-ad3f-779565cef44d">

After `fit_transform`:
<img width="218" alt="Screenshot 2024-03-13 124831" src="https://github.com/IBM/snapml-examples/assets/65911192/550e8b5d-5be6-4bd7-bee2-5a02937a47a4">
<img width="668" alt="image" src="https://github.com/IBM/snapml-examples/assets/65911192/60474ef4-fe1b-40c6-a16a-aeab16e31dc9">

Could you kindly advise? Thank you!

**Comment by paturi1710** [comment]
Is this issue resolved? I am also facing same issue

**Comment by tdoublep** [comment]
Could you please try to call `.ascontiguousarray()` on the numpy array before you pass it to `fit_transform`? We suspect this issue is because internally Snap ML is assuming the data is laid out in row-major format, and perhaps your data is not. 

If this is indeed the issue, it is a bug that should be fixed on our side (we should handle the conversion internally).

**Comment by fabecode** [comment]
Hello, yes, `np.ascontiguousarray(data)` solves the issue. Thank you for your help!

**Comment by tdoublep** [comment]
@fabecode We have now released Snap ML v1.15.5 which contains a fix for this issue. Please re-open if you find it still persists.
