### ISSUE TITLE
Enriched columns after transform doesn't contain source vertex id & target vertex id 

### ISSUE THREAD

**Issue by paturi1710** [IBM/snapml-examples#28]
My Graph feature preprocessor config looks like below (Computing only vertex statistics for 4th column) 

Graph feature preprocessor parameters:  {
    "num_threads": 12,
    "time_window": 1814400,
    "max_no_edges": -1,
    "vertex_stats": true,
    "vertex_stats_tw": 1728000,
    "vertex_stats_cols": [
        4
    ],
    "vertex_stats_feats": [
        0,
        1,
        2,
        3,
        4,
        8,
        9,
        10
    ],
    "fan": false,
    "fan_tw": 86400,
    "fan_bins": [
        2,
        3,
        5
    ],
    "degree": false,
    "degree_tw": 86400,
    "degree_bins": [
        2,
        3,
        5
    ],
    "scatter-gather": false,
    "scatter-gather_tw": 10800,
    "scatter-gather_bins": [
        2,
        3,
        5
    ],
    "temp-cycle": false,
    "temp-cycle_tw": 86400,
    "temp-cycle_bins": [
        2,
        3,
        5
    ],
    "lc-cycle": false,
    "lc-cycle_tw": 86400,
    "lc-cycle_len": 5,
    "lc-cycle_bins": [
        2,
        3,
        5
    ]
}

Edge data looks like below (Edge ID, source vertex id, target vertex id, timestamp & Amount):
Also, Edge ID is unique in the dataset

array([[  28.  ,   31.  ,   31.  ,    0.  , 4523.13],
          [  29.  ,   32.  ,   32.  ,    0.  , 3768.51],
          [  30.  ,   33.  ,   33.  ,    0.  ,  206.48]])

After fit_transform, the returned output looks like below 

array([[28., 29., 30., 31., 32.,  1.,  2.,  2., 32., 64.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  2.,  2., 32., 64.,  0.,  0.,  0.],
       [33., 34., 35., 20., 21.,  1.,  2.,  2., 21., 42.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  2.,  2., 21., 42.,  0.,  0.,  0.],
       [22., 23., 24., 25., 26.,  1.,  2.,  2., 26., 52.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  2.,  2., 26., 52.,  0.,  0.,  0.]])

The original column values are not present and also the statistics computed on Amount column looks not correct. 

My OS is Ubuntu & X_86 architecture. Not able to understand why original edge_id, source/dest vertex ids are not retained after fit_transform.
Can you please help ?

<img width="404" alt="snapml_random_example" src="https://github.com/IBM/snapml-examples/assets/10181406/4e2028f6-7625-49e4-bacb-a55ea5deff3f">

Also, attached one more random example. 

The input example attributes are:
Edge id: 1035676
source vertex id: 122
target vertex id: 103516
Timestamp: 77880
Amount: 721265.91

After transformation, in the enriched outputs only edge id is retained but source vertex & target vertex information got modified.

**Comment by paturi1710** [comment]
Hi, I found the issue. When converting from pandas to numpy array. We need to use copy otherwise you have this problem.

**Comment by tdoublep** [comment]
Re-opening because I do believe this is a bug on our side (see [this comment](https://github.com/IBM/snapml-examples/issues/27#issuecomment-2009131565)). 
 
Could you please also confirm whether calling `.ascontiguousarray` resolves the issue for you? If so, we will issue a patch to Snap ML that does this conversion internally.

**Comment by paturi1710** [comment]
Yes. ascontiguousarray  is solving the issue. Thanks. We will wait for the patch

**Comment by tdoublep** [comment]
@paturi1710 We have now released Snap ML v1.15.5 which contains a fix for this issue. Please re-open if you find it still persists.
