### ISSUE TITLE
Requesting snapml for latest python version

### ISSUE THREAD

**Issue by shivam-maurya-git** [IBM/snapml-examples#30]
It is troublesome to go to lower python version for using snapml and coming back to latest version to use other libraries efficiently. 
Requesting snapml made available for the version 3.12

**Comment by rootsmusic** [comment]
According to the [Installation Guide](https://snapml.readthedocs.io/en/latest/installation.html), Python support is a couple versions behind the latest one.

**Comment by tdoublep** [comment]
That information needs updating. We currently build wheels for Python 3.8, 3.9, 3.10 and 3.11.

Since Python 3.8 is now EOL, we will drop support and add support for 3.12 in the coming weeks.
